# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_curse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='remote_curse.proto',
  package='remotecurse',
  syntax='proto3',
  serialized_options=b'B\020RemoteCurseProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12remote_curse.proto\x12\x0bremotecurse\".\n\x0c\x43urseRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\r\n\x05views\x18\x02 \x01(\x05\"\x1e\n\nCurseReply\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t2K\n\x06HexMan\x12\x41\n\x07\x43urseMe\x12\x19.remotecurse.CurseRequest\x1a\x17.remotecurse.CurseReply\"\x00\x30\x01\x42\x1a\x42\x10RemoteCurseProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_CURSEREQUEST = _descriptor.Descriptor(
  name='CurseRequest',
  full_name='remotecurse.CurseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyword', full_name='remotecurse.CurseRequest.keyword', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='views', full_name='remotecurse.CurseRequest.views', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=81,
)


_CURSEREPLY = _descriptor.Descriptor(
  name='CurseReply',
  full_name='remotecurse.CurseReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='remotecurse.CurseReply.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['CurseRequest'] = _CURSEREQUEST
DESCRIPTOR.message_types_by_name['CurseReply'] = _CURSEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CurseRequest = _reflection.GeneratedProtocolMessageType('CurseRequest', (_message.Message,), {
  'DESCRIPTOR' : _CURSEREQUEST,
  '__module__' : 'remote_curse_pb2'
  # @@protoc_insertion_point(class_scope:remotecurse.CurseRequest)
  })
_sym_db.RegisterMessage(CurseRequest)

CurseReply = _reflection.GeneratedProtocolMessageType('CurseReply', (_message.Message,), {
  'DESCRIPTOR' : _CURSEREPLY,
  '__module__' : 'remote_curse_pb2'
  # @@protoc_insertion_point(class_scope:remotecurse.CurseReply)
  })
_sym_db.RegisterMessage(CurseReply)


DESCRIPTOR._options = None

_HEXMAN = _descriptor.ServiceDescriptor(
  name='HexMan',
  full_name='remotecurse.HexMan',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=115,
  serialized_end=190,
  methods=[
  _descriptor.MethodDescriptor(
    name='CurseMe',
    full_name='remotecurse.HexMan.CurseMe',
    index=0,
    containing_service=None,
    input_type=_CURSEREQUEST,
    output_type=_CURSEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEXMAN)

DESCRIPTOR.services_by_name['HexMan'] = _HEXMAN

# @@protoc_insertion_point(module_scope)
